version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - webnet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - webnet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - webnet

networks:
  webnet:
